#!/bin/sh

bspc config border_width          4
bspc config top_padding           50
bspc config window_gap            10
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config auto_cancel           true
bspc config focus_follows_pointer true

# Colors
bspc config focused_border_color \#2379C2
bspc config normal_border_color none
bspc config presel_border_color none

bspc monitor -d 1 2 3 4 5 6

bspc rule -a Firefox fullscreen=on desktop='^1'

bspc rule -a Subl3 desktop='^2'
bspc rule -a Termite desktop='^2'

bspc rule -a Nautilus state=floating center=on desktop='^3'
bspc rule -a Transmission-gtk state=floating desktop='^3'
bspc rule -a Pinta desktop='^3'
bspc rule -a file-rollex state=floating center=on desktop='^3'
bspc rule -a feh state=floating desktop='^3'
bspc rule -a mplayer state=floating center=on desktop='^3'

bspc rule -a Steam state=floating center=on desktop='^4'
bspc rule -a Battle.net.exe state=floating center=on desktop='^4'
bspc rule -a Hearthstone.exe state=floating center=on desktop='^4'
bspc rule -a mainwindow.py state=floating desktop='^4'

bspc rule -a Pavucontrol state=floating center=on desktop='^5'
bspc rule -a Connman-gtk state=floating center=on desktop='^5'

bspc rule -a Skype state=floating desktop='^6'


xsetroot -cursor_name left_ptr
xset -dpms
xset s off

feh --bg-scale ~/Pictures/bg.png &
~/./.reader.sh | lemonbar -f "fontawesome:size=18" -f "Cantarell:size=14" -g 1900x35+10+8 -p -u 4 &
sxhkd -f 100 &
~/./.lemon.py &
spectrumyzer &
setxkbmap -option caps:none &
compton &